### ISSUE TITLE
lrc file lyrics timestamp issue

### ISSUE THREAD

**Issue by RustedShader** [glomatico/spotify-aac-downloader#17]
# Issue
The timestamp in lrc file are getting stored according to local timezone and not using UTC time so i am getting different results in lrc files.

# Problem
At line 188 in get_lyrics_synced_timestamp_lrc function its not using UTC timezone and using my local timezone by default thus output is

<img width="639" alt="Screenshot 2024-01-19 at 4 16 43 PM" src="https://github.com/glomatico/spotify-aac-downloader/assets/69749260/475e2dc6-de04-4de4-9ecb-7379de88709c">

<img width="611" alt="Screenshot 2024-01-19 at 4 15 08 PM" src="https://github.com/glomatico/spotify-aac-downloader/assets/69749260/23af876e-03df-4159-9bd8-727bce826637">

# Fix
## Instead of using
```lrc_timestamp = datetime.datetime.fromtimestamp(time / 1000.0)```
### Output
```1970-01-01 05:30:02.380000```
### Full Output
```30:02.38```

## You can use
``` lrc_timestamp = datetime.datetime.fromtimestamp(time / 1000.0,tz=datetime.timezone.utc)```
### Output
```1970-01-01 00:00:02.380000+00:00```
### Full Output
```00:02.38```

**Comment by glomatico** [comment]
I will be adding this on the next release.
