### ISSUE TITLE
exclude_tags

### ISSUE THREAD

**Issue by cisko99za** [glomatico/spotify-aac-downloader#19]
first of all BIG thanks for this amazing tool. W-O-N-D-E-R-FU-L

but i've issue to exclude some tags: i don't want add lyrics, comment, disc
so i've open config.json and edit with `"exclude_tags": "lyrics, comment, disc",` 
but work only for lyrics ...
comment and disc (number) still present ...

**Comment by glomatico** [comment]
Hello! Have you tried removing the spaces? Try something like this:
```
"lyrics,comment,disc"
```

**Comment by cisko99za** [comment]
yes, already tried (a lot of tryout ...)
i get 
```
[INFO     18:39:43] (Track 1/1 from URL 1/1) Downloading "Never Gonna Give You Up - 2022 Remaster"
[ERROR    18:39:47] (Track 1/1 from URL 1/1) Failed to download "Never Gonna Give You Up - 2022 Remaster"
[INFO     18:39:47] Done (1 error(s))
```
and no file downloaded ...

**Comment by cisko99za** [comment]
wow you are from Brazil ... very nice place! i've visited, some years ago. amazing

**Comment by glomatico** [comment]
Can you send the output with `--print-exceptions` added to your command?

**Comment by cisko99za** [comment]
```
spotify-aac-downloader "https://open.spotify.com/track/18gqCQzqYb0zvurQPlRkpo" --print-exceptions
[INFO     09:01:37] (Track 1/1 from URL 1/1) Downloading "Never Gonna Give You Up - 2022 Remaster"
[ERROR    09:01:45] (Track 1/1 from URL 1/1) Failed to download "Never Gonna Give You Up - 2022 Remaster"
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\spotify_aac_downloader\cli.py", line 324, in main
    downloader.apply_tags(fixed_location, tags, cover_url)
  File "c:\program files\python38\lib\site-packages\spotify_aac_downloader\downloader.py", line 401, in apply_tags
    mp4_tags["disk"][0][1] = tags["disc_total"]
KeyError: 'disk'
[INFO     09:01:45] Done (1 error(s))
```

**Comment by glomatico** [comment]
> issue also with aria2c on config.json i've add `"aria2c_location": "C:/my_path_to_aria2c",` but i think your tool can use yt-dlp only, not aria2c
> 
> have you discord to talk better ?

You should point the aria2c executable directly, like `"aria2c_location": "C:/my_path_to_aria2c/aria2c.exe"`
